baseURL: 'https://open-feature.github.io/'
languageCode: 'en-us'
title: 'OpenFeature'
theme: "papermod"
relativeUrls: true
enableEmoji: true
paginate: 5

enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
googleAnalytics: "G-HBXXCF17TS"

minify:
    disableXML: true
    # minifyOutput: true

languages:
    en:
        languageName: "English"
        weight: 1
        menu:
            main:
            - name: Overview
              url: home/overview/
              weight: 1
            - name: Specification
              url: https://github.com/open-feature/spec
              weight: 2
            - name: Roadmap
              url: https://github.com/orgs/open-feature/projects/1
              weight: 3
            - name: Community
              url: home/community/
              weight: 4
            - name: Participate
              url: home/participate/
              weight: 5
            - name: GitHub
              url: https://github.com/open-feature
              weight: 6

outputs:
    home:
        - HTML
        - RSS
        - JSON

params:
    env: production # to enable google analytics, opengraph, twitter-cards and schema.
    description: "OpenFeature website"
    author: OpenFeature contributors
    # author: ["Me", "You"] # multiple authors

    defaultTheme: auto
    # disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: true
    # disableSpecial1stPost: true
    displayFullLangName: true
    ShowPostNavLinks: true
    ShowBreadCrumbs: true
    ShowCodeCopyButtons: true
    ShowToc: true
    # comments: false
    images: ["opengraph.png"]

    profileMode:
        enabled: true
        title: " OpenFeature"
        subtitle: >
          OpenFeature is an **open standard** for feature flag management, created to support a
          robust feature flag ecosystem using cloud native technologies. OpenFeature will provide
          a **unified API and SDK**, and a **developer-first, cloud-native implementation**, with
          **extensibility for open source and commercial offerings**.
          <br>
          <br>
          **[>> Sign-up for news <<](https://bit.ly/openfeature-signup)**
        imageUrl: "logo.png"
        imageTitle: Logo
        buttons:
            - name: Learn more
              url: /home/overview/
            - name: Get involved
              url: /home/participate/

    homeInfoParams:
        Title: "OpenFeature - Cloud Native Feature Flag Management"
        Content: >
          Our goal is to create an open standard for feature flag management to support a robust feature flag ecosystem using cloud native technologies.
          The scope includes: Unified API and SDK;
          Developer-first, cloud-native reference implementation; 
          Extensibility for open source and commercial offerings.
          <br>
          <br>
          **[>> Sign-up for news <<](https://bit.ly/openfeature-signup)**
#    socialIcons:
#        - name: github
#          url: "https://github.com/open-feature"

    editPost:
        URL: "https://github.com/open-feature/open-feature.github.io/tree/main/content"
        Text: "Suggest Changes" # edit text
        appendFilePath: true # to append file path to Edit link

taxonomies:
    category: categories
    tag: tags
    series: series

markup:
    goldmark:
        renderer:
            unsafe: true
#     highlight:
#         # anchorLineNos: true
#         codeFences: true
#         guessSyntax: true
#         lineNos: true
#         # noClasses: false
#         style: monokai

privacy:
    vimeo:
        disabled: false
        simple: true

    twitter:
        disabled: false
        enableDNT: true
        simple: true

    instagram:
        disabled: false
        simple: true

    youtube:
        disabled: false
        privacyEnhanced: true

services:
    instagram:
        disableInlineCSS: true
    twitter:
        disableInlineCSS: true
