baseURL: 'https://openfeatureflags.github.io/'
languageCode: 'en-us'
title: 'OpenFeature project'
theme: "papermod"
relativeUrls: true
enableEmoji: true
paginate: 5

enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
# googleAnalytics: UA-123-45

minify:
    disableXML: true
    # minifyOutput: true

languages:
    en:
        languageName: "English"
        weight: 1
        menu:
            main:
            - name: GitHub
              url: https://github.com/openfeatureflags
              weight: 1
            - name: Specification
              url: https://github.com/openfeatureflags/spec
              weight: 2
            - name: Participate
              url: home/participate/
              weight: 3


outputs:
    home:
        - HTML
        - RSS
        - JSON

params:
    env: production # to enable google analytics, opengraph, twitter-cards and schema.
    description: "OpenFeature website"
    author: OpenFeature contributors
    # author: ["Me", "You"] # multiple authors

    defaultTheme: auto
    # disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: true
    # disableSpecial1stPost: true
    displayFullLangName: true
    ShowPostNavLinks: true
    ShowBreadCrumbs: true
    ShowCodeCopyButtons: true
    ShowToc: true
    # comments: false
    images: ["logo.png"]

    profileMode:
        enabled: false
        title: " OpenFeature - Cloud Native Feature Flag Management"
        imageUrl: "#"
        imageTitle: my image
        imageWidth: 120
        imageHeight: 120
        buttons:
            - name: GitHub
              url: https://github.com/openfeatureflags
            - name: Specification
              url: https://github.com/openfeatureflags/spec
            - name: Participate
              url: participate

    homeInfoParams:
        Title: "OpenFeature - Cloud Native Feature Flag Management"
        Content: >
          Our goal is to create an open standard for feature flag management to support a robust feature flag ecosystem using cloud native technologies.
          The scope includes: Unified API and SDK;
          Developer-first, cloud-native reference implementation; 
          Extensibility for open source and commercial offerings.
          <br>
          <br>
          **[>> Sign-up for news <<](https://bit.ly/openfeature-signup)**
    socialIcons:
        - name: github
          url: "https://github.com/openfeatureflags"

    editPost:
        URL: "https://github.com/openfeatureflags/openfeatureflags.github.io/tree/main/content"
        Text: "Suggest Changes" # edit text
        appendFilePath: true # to append file path to Edit link

taxonomies:
    category: categories
    tag: tags
    series: series

markup:
    goldmark:
        renderer:
            unsafe: true
#     highlight:
#         # anchorLineNos: true
#         codeFences: true
#         guessSyntax: true
#         lineNos: true
#         # noClasses: false
#         style: monokai

privacy:
    vimeo:
        disabled: false
        simple: true

    twitter:
        disabled: false
        enableDNT: true
        simple: true

    instagram:
        disabled: false
        simple: true

    youtube:
        disabled: false
        privacyEnhanced: true

services:
    instagram:
        disableInlineCSS: true
    twitter:
        disableInlineCSS: true
